# -*- coding: utf-8 -*-
"""sawera11

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mwTKUK3-oOX9gBkKOsPgxwmOURDY0K09
"""

!pip install face_recognition
!pip install opencv-python
!pip install matplotlib

import os
import cv2
import numpy as np
import matplotlib.pyplot as plt
import face_recognition

os.makedirs("dataset", exist_ok=True)

people = [
    "Imran_Khan",
    "Cristiano_Ronaldo",
    "Lionel_Messi",
    "Elon_Musk",
    "Bill_Gates"
]

for person in people:
    os.makedirs(f"dataset/{person}", exist_ok=True)

print("Dataset folders created successfully!")

dataset_path = "dataset"

known_encodings = []
known_names = []

for person in os.listdir(dataset_path):

    person_folder = os.path.join(dataset_path, person)

    if not os.path.isdir(person_folder):
        continue

    for image_name in os.listdir(person_folder):

        image_path = os.path.join(person_folder, image_name)

        try:
            image = face_recognition.load_image_file(image_path)

            locations = face_recognition.face_locations(image)

            encodings = face_recognition.face_encodings(
                image,
                locations
            )

            for encoding in encodings:
                known_encodings.append(encoding)
                known_names.append(person)

            print("Processed:", image_path)

        except Exception as e:
            print("Error:", image_path, e)

print("\nTotal face samples:", len(known_encodings))
print("People:", set(known_names))

import os
import face_recognition

dataset_path = "dataset"

for person in os.listdir(dataset_path):

    person_folder = os.path.join(dataset_path, person)

    if not os.path.isdir(person_folder):
        continue

    for image_name in os.listdir(person_folder):

        image_path = os.path.join(person_folder, image_name)

        try:
            image = face_recognition.load_image_file(image_path)

            face_locations = face_recognition.face_locations(image)

            landmarks = face_recognition.face_landmarks(
                image,
                face_locations
            )

            print("Person:", person)
            print("Image:", image_name)
            print("Faces detected:", len(landmarks))

            if len(landmarks) > 0:
                print("Facial landmark regions:")
                print(landmarks[0].keys())

            print("-------------------------")

        except Exception as e:
            print("Error:", image_path)
            print(e)

import os
import cv2
import matplotlib.pyplot as plt
import face_recognition

def draw_landmarks(image_path):

    image = face_recognition.load_image_file(image_path)

    landmarks = face_recognition.face_landmarks(image)

    for face in landmarks:
        for points in face.values():
            for x, y in points:
                cv2.circle(image, (x, y), 2, (255, 0, 0), -1)

    plt.figure(figsize=(10, 8))
    plt.imshow(image)
    plt.axis("off")
    plt.show()

import cv2
import matplotlib.pyplot as plt
import face_recognition

def draw_landmarks(image_path):

    image = face_recognition.load_image_file(image_path)

    face_locations = face_recognition.face_locations(image)

    landmarks = face_recognition.face_landmarks(
        image,
        face_locations
    )

    print("Faces detected:", len(landmarks))

    plt.figure(figsize=(10, 8))
    plt.imshow(image)

    for face in landmarks:
        for points in face.values():

            x = [p[0] for p in points]
            y = [p[1] for p in points]

            plt.plot(x, y)

    plt.axis("off")
    plt.show()

import os
import shutil

# Create the correct folders
os.makedirs("/content/dataset/Imran_Khan", exist_ok=True)
os.makedirs("/content/dataset/Cristiano_Ronaldo", exist_ok=True)
os.makedirs("/content/dataset/Lionel_Messi", exist_ok=True)
os.makedirs("/content/dataset/Elon_Musk", exist_ok=True)
os.makedirs("/content/dataset/Bill_Gates", exist_ok=True)

# Move existing uploaded images into their folders

files = os.listdir("/content")

for file in files:

    source = os.path.join("/content", file)

    if not os.path.isfile(source):
        continue

    file_lower = file.lower()

    if "imrankhan" in file_lower:
        shutil.move(
            source,
            "/content/dataset/Imran_Khan/" + file
        )

    elif "cristianoronaldo" in file_lower:
        shutil.move(
            source,
            "/content/dataset/Cristiano_Ronaldo/" + file
        )

    elif "lionelmessi" in file_lower:
        shutil.move(
            source,
            "/content/dataset/Lionel_Messi/" + file
        )

    elif "elon" in file_lower:
        shutil.move(
            source,
            "/content/dataset/Elon_Musk/" + file
        )

    elif "billgate" in file_lower:
        shutil.move(
            source,
            "/content/dataset/Bill_Gates/" + file
        )

print("Images organized successfully!")

import os

dataset_path = "/content/dataset"

for person in os.listdir(dataset_path):

    folder = os.path.join(dataset_path, person)

    if os.path.isdir(folder):

        print("\n" + person + ":")

        for image in os.listdir(folder):
            print("  -", image)

import face_recognition
import matplotlib.pyplot as plt

person = "Imran_Khan"

folder = os.path.join(
    dataset_path,
    person
)

image_name = os.listdir(folder)[0]

image_path = os.path.join(
    folder,
    image_name
)

image = face_recognition.load_image_file(image_path)

face_locations = face_recognition.face_locations(image)

landmarks = face_recognition.face_landmarks(
    image,
    face_locations
)

print("Person:", person)
print("Image:", image_name)
print("Faces detected:", len(landmarks))

plt.figure(figsize=(10, 8))
plt.imshow(image)

for face in landmarks:

    for points in face.values():

        x = [p[0] for p in points]
        y = [p[1] for p in points]

        plt.plot(x, y)

plt.axis("off")
plt.show()

import os
import face_recognition

dataset_path = "/content/dataset"

known_encodings = []
known_names = []

for person in os.listdir(dataset_path):

    person_folder = os.path.join(dataset_path, person)

    if not os.path.isdir(person_folder):
        continue

    for image_name in os.listdir(person_folder):

        image_path = os.path.join(
            person_folder,
            image_name
        )

        try:
            image = face_recognition.load_image_file(image_path)

            face_locations = face_recognition.face_locations(image)

            encodings = face_recognition.face_encodings(
                image,
                face_locations
            )

            for encoding in encodings:
                known_encodings.append(encoding)
                known_names.append(person)

            print("Processed:", person, "-", image_name)

        except Exception as e:
            print("Error:", image_name)
            print(e)

print("\nTotal face encodings:", len(known_encodings))
print("People:", set(known_names))

import cv2
import numpy as np
import matplotlib.pyplot as plt
import face_recognition

def recognize_face(image_path):

    image = face_recognition.load_image_file(image_path)

    locations = face_recognition.face_locations(image)

    encodings = face_recognition.face_encodings(
        image,
        locations
    )

    print("Faces detected:", len(locations))

    for encoding, location in zip(encodings, locations):

        distances = face_recognition.face_distance(
            known_encodings,
            encoding
        )

        best_match = np.argmin(distances)

        if distances[best_match] < 0.50:
            name = known_names[best_match]
        else:
            name = "Unknown"

        top, right, bottom, left = location

        cv2.rectangle(
            image,
            (left, top),
            (right, bottom),
            (0, 255, 0),
            2
        )

        cv2.putText(
            image,
            name,
            (left, top - 10),
            cv2.FONT_HERSHEY_SIMPLEX,
            0.8,
            (0, 255, 0),
            2
        )

    plt.figure(figsize=(10, 8))
    plt.imshow(image)
    plt.axis("off")
    plt.show()

import os
import face_recognition

dataset_path = "/content/dataset"

known_encodings = []
known_names = []

for person in os.listdir(dataset_path):

    person_folder = os.path.join(dataset_path, person)

    if not os.path.isdir(person_folder):
        continue

    for image_name in os.listdir(person_folder):

        image_path = os.path.join(
            person_folder,
            image_name
        )

        try:
            image = face_recognition.load_image_file(image_path)

            face_locations = face_recognition.face_locations(image)

            encodings = face_recognition.face_encodings(
                image,
                face_locations
            )

            for encoding in encodings:
                known_encodings.append(encoding)
                known_names.append(person)

            print("Processed:", person, "-", image_name)

        except Exception as e:
            print("Error:", image_name)
            print(e)

print("\nTotal encodings:", len(known_encodings))
print("Names:", known_names)

import numpy as np
import cv2
import matplotlib.pyplot as plt
import face_recognition

def recognize_face(image_path):

    image = face_recognition.load_image_file(image_path)

    locations = face_recognition.face_locations(image)

    encodings = face_recognition.face_encodings(
        image,
        locations
    )

    print("Faces detected:", len(locations))

    for encoding, location in zip(encodings, locations):

        distances = face_recognition.face_distance(
            known_encodings,
            encoding
        )

        best_match = np.argmin(distances)

        if distances[best_match] < 0.50:
            name = known_names[best_match]
        else:
            name = "Unknown"

        top, right, bottom, left = location

        cv2.rectangle(
            image,
            (left, top),
            (right, bottom),
            (0, 255, 0),
            2
        )

        cv2.putText(
            image,
            name,
            (left, top - 10),
            cv2.FONT_HERSHEY_SIMPLEX,
            0.8,
            (0, 255, 0),
            2
        )

    plt.figure(figsize=(10, 8))
    plt.imshow(image)
    plt.axis("off")
    plt.show()

import os
import face_recognition
import numpy as np
import cv2
import matplotlib.pyplot as plt

dataset_path = "/content/dataset"

# Create face encodings from the dataset
known_encodings = []
known_names = []

for person in os.listdir(dataset_path):

    person_folder = os.path.join(dataset_path, person)

    if not os.path.isdir(person_folder):
        continue

    for image_name in os.listdir(person_folder):

        image_path = os.path.join(
            person_folder,
            image_name
        )

        try:
            image = face_recognition.load_image_file(image_path)

            locations = face_recognition.face_locations(image)

            encodings = face_recognition.face_encodings(
                image,
                locations
            )

            for encoding in encodings:
                known_encodings.append(encoding)
                known_names.append(person)

        except Exception as e:
            print("Error:", image_name, e)


print("Total face encodings:", len(known_encodings))
print("People:", set(known_names))


# Test Imran Khan image
person = "Imran_Khan"

folder = os.path.join(
    dataset_path,
    person
)

images = os.listdir(folder)

image_name = images[0]

image_path = os.path.join(
    folder,
    image_name
)

print("Testing:", image_name)


# Load test image
image = face_recognition.load_image_file(image_path)

locations = face_recognition.face_locations(image)

encodings = face_recognition.face_encodings(
    image,
    locations
)

print("Faces detected:", len(locations))


# Recognize faces
for encoding, location in zip(encodings, locations):

    distances = face_recognition.face_distance(
        known_encodings,
        encoding
    )

    best_match = np.argmin(distances)

    if distances[best_match] < 0.50:
        name = known_names[best_match]
    else:
        name = "Unknown"

    top, right, bottom, left = location

    cv2.rectangle(
        image,
        (left, top),
        (right, bottom),
        (0, 255, 0),
        2
    )

    cv2.putText(
        image,
        name,
        (left, top - 10),
        cv2.FONT_HERSHEY_SIMPLEX,
        0.8,
        (0, 255, 0),
        2
    )


# Show result
plt.figure(figsize=(10, 8))
plt.imshow(image)
plt.axis("off")
plt.show()

import os
import face_recognition
import numpy as np

dataset_path = "/content/dataset"

correct = 0
total = 0

for person in os.listdir(dataset_path):

    person_folder = os.path.join(dataset_path, person)

    if not os.path.isdir(person_folder):
        continue

    for image_name in os.listdir(person_folder):

        image_path = os.path.join(
            person_folder,
            image_name
        )

        try:

            image = face_recognition.load_image_file(
                image_path
            )

            locations = face_recognition.face_locations(
                image
            )

            encodings = face_recognition.face_encodings(
                image,
                locations
            )

            for encoding in encodings:

                distances = face_recognition.face_distance(
                    known_encodings,
                    encoding
                )

                best_match = np.argmin(distances)

                if distances[best_match] < 0.50:
                    predicted = known_names[best_match]
                else:
                    predicted = "Unknown"

                total += 1

                if predicted == person:
                    correct += 1

                print(
                    "Actual:",
                    person,
                    "| Predicted:",
                    predicted
                )

        except Exception as e:

            print(
                "Error:",
                image_name,
                "|",
                e
            )

print("\n========================")
print("Total faces tested:", total)
print("Correct predictions:", correct)

if total > 0:
    accuracy = (correct / total) * 100
    print("Accuracy:", round(accuracy, 2), "%")

import cv2
import matplotlib.pyplot as plt

person = "Imran_Khan"

folder = os.path.join(
    dataset_path,
    person
)

image_name = os.listdir(folder)[0]

image_path = os.path.join(
    folder,
    image_name
)

image = face_recognition.load_image_file(
    image_path
)

locations = face_recognition.face_locations(
    image
)

encodings = face_recognition.face_encodings(
    image,
    locations
)

landmarks = face_recognition.face_landmarks(
    image,
    locations
)

output = image.copy()

for i, location in enumerate(locations):

    top, right, bottom, left = location

    # Recognition
    distances = face_recognition.face_distance(
        known_encodings,
        encodings[i]
    )

    best_match = np.argmin(distances)

    if distances[best_match] < 0.50:
        name = known_names[best_match]
    else:
        name = "Unknown"

    # Face box
    cv2.rectangle(
        output,
        (left, top),
        (right, bottom),
        (0, 255, 0),
        2
    )

    # Name
    cv2.putText(
        output,
        name,
        (left, top - 10),
        cv2.FONT_HERSHEY_SIMPLEX,
        0.8,
        (0, 255, 0),
        2
    )

    # 68 facial landmarks
    for points in landmarks[i].values():

        for x, y in points:

            cv2.circle(
                output,
                (x, y),
                2,
                (255, 0, 0),
                -1
            )

plt.figure(figsize=(12, 9))
plt.imshow(output)
plt.axis("off")
plt.show()

print("========== PROJECT SUMMARY ==========")
print("Dataset location:", dataset_path)
print("People in dataset:", set(known_names))
print("Total face encodings:", len(known_encodings))
print("Total faces tested:", total)
print("Correct predictions:", correct)

if total > 0:
    print("Recognition accuracy:", round((correct / total) * 100, 2), "%")

print("68-point facial landmark extraction: Completed")
print("Face recognition: Completed")
print("Dataset processing: Completed")

import os
import face_recognition
import numpy as np
import cv2
import matplotlib.pyplot as plt

person = "Imran_Khan"

folder = os.path.join(
    dataset_path,
    person
)

images = os.listdir(folder)

# Use the second image
image_name = images[1]

image_path = os.path.join(
    folder,
    image_name
)

print("Testing new image:", image_name)

image = face_recognition.load_image_file(image_path)

locations = face_recognition.face_locations(image)

encodings = face_recognition.face_encodings(
    image,
    locations
)

landmarks = face_recognition.face_landmarks(
    image,
    locations
)

output = image.copy()

for i, location in enumerate(locations):

    # Recognition
    distances = face_recognition.face_distance(
        known_encodings,
        encodings[i]
    )

    best_match = np.argmin(distances)

    if distances[best_match] < 0.50:
        name = known_names[best_match]
    else:
        name = "Unknown"

    top, right, bottom, left = location

    # Draw face box
    cv2.rectangle(
        output,
        (left, top),
        (right, bottom),
        (0, 255, 0),
        2
    )

    # Draw name
    cv2.putText(
        output,
        name,
        (left, top - 10),
        cv2.FONT_HERSHEY_SIMPLEX,
        0.8,
        (0, 255, 0),
        2
    )

    # Draw facial landmarks
    for points in landmarks[i].values():

        for x, y in points:

            cv2.circle(
                output,
                (x, y),
                2,
                (255, 0, 0),
                -1
            )

print("Faces detected:", len(locations))
print("Recognition result:", name)

plt.figure(figsize=(12, 9))
plt.imshow(output)
plt.axis("off")
plt.show()